### ISSUE TITLE
Crash during combat: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#16]
Happened during worldmap random encounter after everything loaded, when the AI took it's turn (AI was first to play).
Fight was against Lantern Archon x3 (fly, ranged, doom).
I had another fight going fine vs the same mobs with same party.

Log:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 (class java.lang.RuntimeException)
javelin.controller.ai.ThreadManager.think(ThreadManager.java:68)
javelin.view.screen.BattleScreen.computerTurn(BattleScreen.java:350)
javelin.view.screen.BattleScreen.humanTurn(BattleScreen.java:193)
javelin.view.screen.BattleScreen.step(BattleScreen.java:181)
javelin.view.screen.BattleScreen.mainLoop(BattleScreen.java:166)
javelin.controller.exception.battle.StartBattle.battle(StartBattle.java:65)
javelin.JavelinApp.loop(JavelinApp.java:137)
javelin.JavelinApp.run(JavelinApp.java:112)
java.lang.Thread.run(Unknown Source)

Index: 0, Size: 0 (class java.lang.IndexOutOfBoundsException)
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
javelin.controller.action.Charge.usedefaultattack(Charge.java:94)
javelin.controller.action.Charge.charge(Charge.java:61)
javelin.controller.action.Charge.getoutcomes(Charge.java:164)
javelin.controller.ai.ActionProvider.next(ActionProvider.java:87)
javelin.controller.ai.ActionProvider.next(ActionProvider.java:96)
javelin.controller.ai.ActionProvider.next(ActionProvider.java:96)
javelin.controller.ai.ActionProvider.next(ActionProvider.java:1)
javelin.controller.ai.valueselector.ValueSelector.getValue(ValueSelector.java:89)
javelin.controller.ai.AlphaBetaSearch.alphaBetaSearch(AlphaBetaSearch.java:78)
javelin.controller.ai.AiThread.run(AiThread.java:45)

```

**Comment by tukkek** [comment]
It's good that you're testing the late game since I feel it's largely unexplored. I myself haven't gotten to it during normal play. Unfortunately any relevant change in the code requires me to start a new save so I'm always required to restart as I work on the project...

The error seems to be occurring on charge action logic but since charge is one of the first actions to be computed it could also denote a general error in the battle state. Like in the past "empty charge solution" was a symptom for "stacked combatants" (more than one unit on the same tile, which is illegal). Just a note to myself here.

**Comment by tukkek** [comment]
This could have been fixed by closing #14. Let me know if it happens again.

**Comment by 11132113** [comment]
Closing this until i see it again.

**Comment by tukkek** [comment]
Thank you. I wanted to close the remaining short-term issues yesterday but couldn't get around to it https://github.com/tukkek/javelin/milestones/Short-term Hopefully I'll be able to do that by the end of the day today. They seem fairly manageable.

The artist is also working on some new images for the world map. Depending on his work and the bugs here I'm planning on releasing it next friday. There is no hurry though - if something else comes up let me know and if necessary I"ll postpone the release date :) thanks again for the great help!
