### ISSUE TITLE
Killed enemies can't be walked through but can be charged through

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#19]

**Comment by tukkek** [comment]
I'm sure the code is written in a way as to prevent that. It's possible that either there is a bug or that the charge path found an alternate way through the "corpse". Can you clarify to me if the charging unit "passed over" the skull or if it "landed" on top of it (next to the target enemy)?  

Thanks for the new batch of bug reports :D I'm quite glad that we're going from game-crashing, save-losing bugs to stuff that is less terrible haha (though let me know if the old bugs reappear). I'll find time to work on these new ones today.

**Comment by tukkek** [comment]
Fixed! Will let you know of a new version when closing another issue, as I work through them.
