### ISSUE TITLE
Windows 10 error on exiting Academy

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#282]
b4fc1617 (HEAD -> 1.7) SquadScreen fix
System: Windows 10 10.0 amd64 

null (class java.lang.NullPointerException)
javelin/javelin.view.mappanel.Tile.drawcover(Tile.java:67)
javelin/javelin.view.mappanel.world.WorldTile.paint(WorldTile.java:39)
javelin/javelin.view.mappanel.Tile.repaint(Tile.java:55)
javelin/javelin.view.mappanel.world.WorldPanel.refresh(WorldPanel.java:62)
javelin/javelin.Javelin.redraw(Javelin.java:414)
javelin/javelin.view.screen.WorldScreen.move(WorldScreen.java:134)
javelin/javelin.view.screen.WorldScreen.turn(WorldScreen.java:181)
javelin/javelin.JavelinApp.loop(JavelinApp.java:105)
javelin/javelin.JavelinApp.run(JavelinApp.java:86)
java.base/java.lang.Thread.run(Thread.java:835)

Always a fatal crash. New Java patch, updated 4/4/21

**Comment by Spiralrazor369** [comment]
Latest version of Javelin installed

**Comment by tukkek** [comment]
Uploaded an unstable release as discussed on Discord:

https://github.com/tukkek/javelin/releases/tag/1.7b20

**Comment by tukkek** [comment]
Thank you and welcome to GitHub, by the way, @Spiralrazor369 ! :)
