### ISSUE TITLE
Crash on entering Forest path dungeon.

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#286]
Unsure if this one is a known issue but it comes across as Summon related and i hadnt seen it before:

cbab5d4a (HEAD -> 1.7, origin/1.7) Fixing Summon type collision for instances
System: Windows 10 10.0 amd64

dungeon\terrain\dirt (pwd=C:\Users\SR\Desktop\Javelin\javelin) (class java.lang.RuntimeException)
javelin/javelin.view.Images.get(Images.java:117)
javelin/javelin.view.Images.get(Images.java:123)
javelin/javelin.old.underground.Caves.<init>(Caves.java:34)
javelin/javelin.old.underground.Caves.<init>(Caves.java:45)
javelin/javelin.controller.content.terrain.Underground.getmaps(Underground.java:36)
javelin/javelin.controller.content.fight.RandomDungeonEncounter.set(RandomDungeonEncounter.java:35)
javelin/javelin.controller.content.fight.RandomDungeonEncounter.<init>(RandomDungeonEncounter.java:28)
javelin/javelin.model.world.location.dungeon.Dungeon.fight(Dungeon.java:294)
javelin/javelin.model.world.location.dungeon.Wilderness.fight(Wilderness.java:265)
javelin/javelin.view.screen.DungeonScreen.encounter(DungeonScreen.java:96)
javelin/javelin.controller.content.fight.RandomEncounter.encounter(RandomEncounter.java:26)
javelin/javelin.model.world.location.dungeon.DungeonFloor.explore(DungeonFloor.java:555)
javelin/javelin.view.screen.DungeonScreen.explore(DungeonScreen.java:35)
javelin/javelin.controller.content.action.world.WorldMove.move(WorldMove.java:105)
javelin/javelin.controller.content.action.world.WorldMove.perform(WorldMove.java:89)
javelin/javelin.view.screen.WorldScreen.perform(WorldScreen.java:167)
javelin/javelin.view.screen.WorldScreen.act(WorldScreen.java:146)
javelin/javelin.view.screen.WorldScreen.turn(WorldScreen.java:185)
javelin/javelin.JavelinApp.loop(JavelinApp.java:96)
javelin/javelin.JavelinApp.run(JavelinApp.java:81)
java.base/java.lang.Thread.run(Thread.java:832)

Can't read input file! (class javax.imageio.IIOException)
java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
javelin/javelin.view.Images.get(Images.java:105)
javelin/javelin.view.Images.get(Images.java:123)
javelin/javelin.old.underground.Caves.<init>(Caves.java:34)
javelin/javelin.old.underground.Caves.<init>(Caves.java:45)
javelin/javelin.controller.content.terrain.Underground.getmaps(Underground.java:36)
javelin/javelin.controller.content.fight.RandomDungeonEncounter.set(RandomDungeonEncounter.java:35)
javelin/javelin.controller.content.fight.RandomDungeonEncounter.<init>(RandomDungeonEncounter.java:28)
javelin/javelin.model.world.location.dungeon.Dungeon.fight(Dungeon.java:294)
javelin/javelin.model.world.location.dungeon.Wilderness.fight(Wilderness.java:265)
javelin/javelin.view.screen.DungeonScreen.encounter(DungeonScreen.java:96)
javelin/javelin.controller.content.fight.RandomEncounter.encounter(RandomEncounter.java:26)
javelin/javelin.model.world.location.dungeon.DungeonFloor.explore(DungeonFloor.java:555)
javelin/javelin.view.screen.DungeonScreen.explore(DungeonScreen.java:35)
javelin/javelin.controller.content.action.world.WorldMove.move(WorldMove.java:105)
javelin/javelin.controller.content.action.world.WorldMove.perform(WorldMove.java:89)
javelin/javelin.view.screen.WorldScreen.perform(WorldScreen.java:167)
javelin/javelin.view.screen.WorldScreen.act(WorldScreen.java:146)
javelin/javelin.view.screen.WorldScreen.turn(WorldScreen.java:185)
javelin/javelin.JavelinApp.loop(JavelinApp.java:96)
javelin/javelin.JavelinApp.run(JavelinApp.java:81)
java.base/java.lang.Thread.run(Thread.java:832)

**Comment by tukkek** [comment]
It's a missing image file, apparently. I'll look into it.
