### ISSUE TITLE
Crash immediately after training base class kit at Adventures Guild

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#290]
23dffaab (HEAD -> 1.7) Fix #288 (recruit on guild with rubies)
System: Windows 10 10.0 amd64

null (class java.util.ConcurrentModificationException)
java.base/java.util.ArrayList.writeObject(ArrayList.java:870)
java.base/jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1931)
java.base/java.util.HashMap.writeObject(HashMap.java:1501)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
javelin/javelin.controller.db.StateManager$SaveThread.run(StateManager.java:59)

**Comment by Spiralrazor369** [comment]
23dffaab (HEAD -> 1.7) Fix #288 (recruit on guild with rubies)
System: Windows 10 10.0 amd64

null (class java.util.ConcurrentModificationException)
java.base/java.util.ArrayList.writeObject(ArrayList.java:870)
java.base/jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1931)
java.base/java.util.HashMap.writeObject(HashMap.java:1501)
java.base/jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
javelin/javelin.controller.db.StateManager$SaveThread.run(StateManager.java:59)

**Comment by tukkek** [comment]
Closing for now as @Spiralrazor369 has reported the issue not happening again for now. If the error happens again, try bumping the `saveinterval` and `backupinterval` options to something like 10 or 15 minutes and see if it helps.

Have not been able to reproduce it so far on my systems.

Feel free to re-open if the error resurfaces.

**Comment by tukkek** [comment]
I believe I have reproduced and fixed the issue. Here's the full solution as documented in the code:

    The current save strategy is:

    1. Will always force a save when entering battle. At this point the player
    won't be interacting with the {@link World}, which means data won't be
    modified while a save is in progress. This is the ideal scenario as it's
    seamless to the player and happens in a background thread.

    2. Will always check before a player acts in the {@link World} if the
    auto-save timer has expired and if so, will trigger a save. This should be
    rare, as the default auto-save interval is 10 minutes and forced saves while
    the player is doing battle (#1) will naturally reset the timer as they occur.

    3. In the rare case that a save happens outside of battle, the game will show
    a message and {@link SaveThread#hold()} until the save is completed. While
    relatively fast, this is annoying but should happen only rarely. Players are
    always free to change the auto-save interval (or disable it entirely) to suit
    their personal preferences as well.

    4. Backup saves are made according to the configured interval (30 minutes by
    default) and are triggered automatically as part of any save action
    immediately after the main save is completed.

    5. A save is always forced upon closing the game window - then a backup save
    as well (unless backups are disabled entirely).
