### ISSUE TITLE
Unsure what this is.....

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#291]
23dffaab (HEAD -> 1.7) Fix #288 (recruit on guild with rubies)
System: Windows 10 10.0 amd64

null (class java.util.ConcurrentModificationException)
java.base/java.util.ArrayList.writeObject(ArrayList.java:870)
java.base/jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
java.base/java.util.ArrayList.writeObject(ArrayList.java:866)
java.base/jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1931)
java.base/java.util.HashMap.writeObject(HashMap.java:1501)
java.base/jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1186)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
javelin/javelin.controller.db.StateManager$SaveThread.run(StateManager.java:59)

**Comment by tukkek** [comment]
That is the same as #290, it only failed at a different point of the saving process.
