### ISSUE TITLE
Crash on equipping Ring of Protection+1

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#295]
2da7bb01 (HEAD -> 1.7, origin/1.7) Haunts begin at Mid Tier and adding flexibility to Wave generation #293
System: Windows 10 10.0 amd64

class javelin.model.item.gear.RingOfProtection cannot be cast to class javelin.model.item.gear.rune.RuneGear (javelin.model.item.gear.RingOfProtection and javelin.model.item.gear.rune.RuneGear are in module javelin of loader 'app') (class java.lang.ClassCastException)
javelin/javelin.controller.content.action.world.inventory.EquipGear.use(EquipGear.java:35)
javelin/javelin.controller.content.action.world.inventory.UseItems.executecommand(UseItems.java:86)
javelin/javelin.controller.content.action.world.inventory.UseItems.perform(UseItems.java:61)
javelin/javelin.view.screen.WorldScreen.perform(WorldScreen.java:161)
javelin/javelin.view.screen.WorldScreen.act(WorldScreen.java:147)
javelin/javelin.view.screen.WorldScreen.turn(WorldScreen.java:195)
javelin/javelin.JavelinApp.loop(JavelinApp.java:96)
javelin/javelin.JavelinApp.run(JavelinApp.java:81)
java.base/java.lang.Thread.run(Thread.java:832)

**Comment by tukkek** [comment]
This was a very silly mistake where I wrote `(RuneGear)i` where it should've been `(Gear)i`, on the Equp Gear Screen code - so trying to equip anything that wasn't Rune Gear in specific would end up throwing an error.
