### ISSUE TITLE
Possible tile issue?

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#297]
a190e87b (HEAD -> 1.7, origin/1.7) Removing Urban Events that spontaneously swing reputation
System: Windows 10 10.0 amd64

null (class java.lang.NullPointerException)
javelin/javelin.view.mappanel.Tile.repaint(Tile.java:63)
javelin/javelin.view.mappanel.MapPanel$1.paint(MapPanel.java:39)
java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5073)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Spiralrazor369** [comment]
Has this happen in a Keep Dungeon as well:

a190e87b (HEAD -> 1.7, origin/1.7) Removing Urban Events that spontaneously swing reputation
System: Windows 10 10.0 amd64

null (class java.lang.NullPointerException)
javelin/javelin.view.mappanel.Tile.repaint(Tile.java:63)
javelin/javelin.view.mappanel.MapPanel$1.paint(MapPanel.java:39)
java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5073)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tukkek** [comment]
I'm going to need more info on this:

1. Were you just on the Keep or was that during a battle or when a battle was starting?
2. Did the map draw at all at first or did it crash as you were entering (immediately, before drawing anything)?
3. Does it happen every time you enter a particular Keep? Any Keep?
4. Does it happen sometimes only or every time you do something?

Any extra information would be helpful. Right now all I can do is add more information to the error message for next time the error happens.

**Comment by tukkek** [comment]
New report with more details in #304.

**Comment by Spiralrazor369** [comment]
This one happened when a village was occupied, it happened during the attack after partially loading the tactical map.

yep, repeatable.  I reloaded from a previous save and went to the same village, same error.

Only happens on certain maps. I was fine with this play through except when i try to load to that particular village.

**Comment by tukkek** [comment]
Thanks, this helps already and if you can attach a save file if you see this happening again ti would be also very helpful!
