### ISSUE TITLE
Random malus to dexterity

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#298]
dexterity went from 15 to 1,  no conditions listed. Unrecoverable with Inn rest, had to buy the stat up to 15 via Academy.
Wasnt able to test lessor restoration on it as i didnt have the spell.

**Comment by tukkek** [comment]
Here are the things that change dexterity, let me know if any of them sounds like something that you may have used/encountered:

1. The Cat's Grace spell or the Graceful item enchantment
2. Being paralyzed
3. Being exhausted, from the Ray of Exhaustion spell

For now I have attempted a more general fix that will make the AI a little slower but hopefully not by a lot. It could very well solve the problem so I'm closing the issue for now. If you reply with more information of if the error happens again, feel free to reopen and I will test more deeply.
