### ISSUE TITLE
Potentila new tile issue, latest version

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#304]
c4af3ae2 (HEAD -> 1.7, origin/1.7) Fixing #300 (`super.extend()` was not bieng called)
System: Windows 10 10.0 amd64

Screen: javelin.view.screen.BattleScreen[panel0,0,0,0x0,invalid,layout=java.awt.BorderLayout]
Panel: javelin.view.mappanel.battle.BattlePanel[panel1,0,0,0x0,invalid,layout=java.awt.FlowLayout]
Graphics: sun.java2d.SunGraphics2D[font=java.awt.Font[family=Monospaced,name=Monospaced,style=bold,size=15],color=java.awt.Color[r=255,g=255,b=255]] (class java.lang.RuntimeException)
javelin/javelin.view.mappanel.Tile.repaint(Tile.java:72)
javelin/javelin.view.mappanel.MapPanel$1.paint(MapPanel.java:39)
java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5073)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

null (class java.lang.NullPointerException)
javelin/javelin.view.mappanel.Tile.repaint(Tile.java:64)
javelin/javelin.view.mappanel.MapPanel$1.paint(MapPanel.java:39)
java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5073)
java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tukkek** [comment]
Closing in favor of #297.
